### ISSUE TITLE
캘린더 데이터 형식

### ISSUE THREAD

**Issue by JiseongSon381** [2023OSSL/2023OSSL_Mini-Project#2]
캘린더에서 각 날짜별로 일정을 추가하는 프로그램을 구현하니까 데이터를 어떻게 다뤄야 할 지 정해야 할 것 같습니다.
데이터 폴더를 만들어서 일정을 추가하면 그 날짜이름의 txt파일을 만들어서 일정에 대한 데이터를 다루는 방식은 어떠실까요?

ex)
user input: oss 중간고사 / (2023-04-18)
---> file name: 20230418.txt
---> file contents: oss 중간고사

파일 경로: main/schedule/...

**Comment by solseye** [comment]
좋은것 같습니다! 일정을 추가할때마다 그 해당 날짜의 이름으로 폴더가 생성되고, 그 안에 세부 일정이 추가되면 될 것 같습니다!

**Comment by JiseongSon381** [comment]
넵! 그러면 일정 데이터 형식은 이렇게 확정 짓는 걸로 하겠습니다!

**Comment by JiseongSon381** [comment]
데이터를 날짜 이름으로 해서 여러 파일을 만들어서 관리하는게 생각보다 까다로워서 데이터 관리 부분을 좀 수정해야 할 것 같습니다. 하나의 텍스트 파일에서 3줄 씩 (날짜, 일정 제목, 일정 내용) 구분해서 데이터를 다루는 게 어떠실까요?
